### PR TITLE
Graph upgrade

### LINKED ISSUE #49: update graph if signal is scalar constant (virtual node)

### PR DESCRIPTION
**Pull request by dakridas**
closes #49

### CODE REVIEW

**Comment by paraschas** [comment]
:+1:

Will check tomorrow.

**Comment by paraschas** [comment]
Works good, but module_instances produces an error:

```
[+] parsing file tests/module_instances.v
[+] 5: instance -> type: module_a, name: instance_1, connections: { signal1, NoSignal, signal2, NoSignal }
[+] searching ports of module module_a
[-] no element for module_a at map
[-] search failed
[-] exit
```

**Comment by dakridas** [comment]
it is correct.. you have not library with module_a

**Comment by paraschas** [comment]
Yes... Of course!

**Pull request merged**
