### PR TITLE
Manage memory

### PR DESCRIPTION
**Pull request by dakridas**

### CODE REVIEW

**Comment by paraschas** [comment]
I get a segmentation fault in all the tests I run.

Does it run correctly in your machine?

**Comment by dakridas** [comment]
Yes the tests folder has change and the paths are wrong

**Comment by paraschas** [comment]
Haven't the paths of the tests been updated by git? Which paths are still wrong?

**Comment by dakridas** [comment]
the paths in the makefile..

**Comment by paraschas** [comment]
I see. I believe this should be fixed before merging.

**Pull request merged**
